/*
 * This file is generated by jOOQ.
 */
package de.fiereu.openmmo.server.login.jooq.routines


import de.fiereu.openmmo.server.login.jooq.Public

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class FipsMode : AbstractRoutine<Boolean>("fips_mode", Public.PUBLIC, DSL.comment(""), SQLDataType.BOOLEAN) {
    companion object {

        /**
         * The parameter <code>public.fips_mode.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Boolean?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BOOLEAN, false, false)
    }

    init {
        returnParameter = FipsMode.RETURN_VALUE
    }
}
