/*
 * This file is generated by jOOQ.
 */
package de.fiereu.openmmo.server.login.jooq.tables


import de.fiereu.openmmo.server.login.jooq.Public
import de.fiereu.openmmo.server.login.jooq.keys.USER_TOKEN_PKEY
import de.fiereu.openmmo.server.login.jooq.keys.USER_TOKEN_TOKEN_KEY
import de.fiereu.openmmo.server.login.jooq.keys.USER_TOKEN_USER_ID_KEY
import de.fiereu.openmmo.server.login.jooq.keys.USER_TOKEN__USER_TOKEN_USER_ID_FKEY
import de.fiereu.openmmo.server.login.jooq.tables.User.UserPath
import de.fiereu.openmmo.server.login.jooq.tables.records.UserTokenRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UserToken(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UserTokenRecord>?,
    parentPath: InverseForeignKey<out Record, UserTokenRecord>?,
    aliased: Table<UserTokenRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<UserTokenRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.user_token</code>
         */
        val USER_TOKEN: UserToken = UserToken()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UserTokenRecord> = UserTokenRecord::class.java

    /**
     * The column <code>public.user_token.id</code>.
     */
    val ID: TableField<UserTokenRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.user_token.created_at</code>.
     */
    val CREATED_AT: TableField<UserTokenRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.user_token.user_id</code>.
     */
    val USER_ID: TableField<UserTokenRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.user_token.token</code>.
     */
    val TOKEN: TableField<UserTokenRecord, ByteArray?> = createField(DSL.name("token"), SQLDataType.BLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<UserTokenRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UserTokenRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<UserTokenRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.user_token</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.user_token</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.user_token</code> table reference
     */
    constructor(): this(DSL.name("user_token"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UserTokenRecord>?, parentPath: InverseForeignKey<out Record, UserTokenRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, USER_TOKEN, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class UserTokenPath : UserToken, Path<UserTokenRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UserTokenRecord>?, parentPath: InverseForeignKey<out Record, UserTokenRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<UserTokenRecord>): super(alias, aliased)
        override fun `as`(alias: String): UserTokenPath = UserTokenPath(DSL.name(alias), this)
        override fun `as`(alias: Name): UserTokenPath = UserTokenPath(alias, this)
        override fun `as`(alias: Table<*>): UserTokenPath = UserTokenPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<UserTokenRecord, Int?> = super.getIdentity() as Identity<UserTokenRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<UserTokenRecord> = USER_TOKEN_PKEY
    override fun getUniqueKeys(): List<UniqueKey<UserTokenRecord>> = listOf(USER_TOKEN_TOKEN_KEY, USER_TOKEN_USER_ID_KEY)
    override fun getReferences(): List<ForeignKey<UserTokenRecord, *>> = listOf(USER_TOKEN__USER_TOKEN_USER_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    fun user(): UserPath = user
    val user: UserPath by lazy { UserPath(this, USER_TOKEN__USER_TOKEN_USER_ID_FKEY, null) }
    override fun `as`(alias: String): UserToken = UserToken(DSL.name(alias), this)
    override fun `as`(alias: Name): UserToken = UserToken(alias, this)
    override fun `as`(alias: Table<*>): UserToken = UserToken(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserToken = UserToken(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserToken = UserToken(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UserToken = UserToken(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): UserToken = UserToken(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): UserToken = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): UserToken = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): UserToken = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): UserToken = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): UserToken = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): UserToken = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): UserToken = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): UserToken = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): UserToken = where(DSL.notExists(select))
}
