/*
 * This file is generated by jOOQ.
 */
package de.fiereu.openmmo.db.jooq.tables.records;


import de.fiereu.openmmo.db.jooq.tables.ServerNode;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.postgres.extensions.types.Inet;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ServerNodeRecord extends UpdatableRecordImpl<ServerNodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.server_node.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.server_node.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.server_node.server_id</code>.
     */
    public void setServerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.server_node.server_id</code>.
     */
    public Integer getServerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.server_node.ipv4</code>.
     */
    public void setIpv4(Inet value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.server_node.ipv4</code>.
     */
    public Inet getIpv4() {
        return (Inet) get(2);
    }

    /**
     * Setter for <code>public.server_node.ipv6</code>.
     */
    public void setIpv6(Inet value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.server_node.ipv6</code>.
     */
    public Inet getIpv6() {
        return (Inet) get(3);
    }

    /**
     * Setter for <code>public.server_node.port</code>.
     */
    public void setPort(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.server_node.port</code>.
     */
    public Integer getPort() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.server_node.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.server_node.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServerNodeRecord
     */
    public ServerNodeRecord() {
        super(ServerNode.SERVER_NODE);
    }

    /**
     * Create a detached, initialised ServerNodeRecord
     */
    public ServerNodeRecord(Integer id, Integer serverId, Inet ipv4, Inet ipv6, Integer port, LocalDateTime createdAt) {
        super(ServerNode.SERVER_NODE);

        setId(id);
        setServerId(serverId);
        setIpv4(ipv4);
        setIpv6(ipv6);
        setPort(port);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
