/*
 * This file is generated by jOOQ.
 */
package de.fiereu.openmmo.db.jooq.tables.records;


import de.fiereu.openmmo.db.jooq.tables.Server;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ServerRecord extends UpdatableRecordImpl<ServerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.server.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.server.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.server.type</code>.
     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.server.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.server.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.server.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.server.port</code>.
     */
    public void setPort(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.server.port</code>.
     */
    public Integer getPort() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.server.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.server.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServerRecord
     */
    public ServerRecord() {
        super(Server.SERVER);
    }

    /**
     * Create a detached, initialised ServerRecord
     */
    public ServerRecord(Integer id, String type, String name, Integer port, LocalDateTime createdAt) {
        super(Server.SERVER);

        setId(id);
        setType(type);
        setName(name);
        setPort(port);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
