@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package de.fiereu.openmmo.server.login.jooq.tables.references


import de.fiereu.openmmo.server.login.jooq.tables.User
import de.fiereu.openmmo.server.login.jooq.tables.UserToken



/**
 * The table <code>public.user</code>.
 */
val USER: User = User.USER

/**
 * The table <code>public.user_token</code>.
 */
val USER_TOKEN: UserToken = UserToken.USER_TOKEN
