/*
 * This file is generated by jOOQ.
 */
package de.fiereu.openmmo.db.jooq.tables;


import de.fiereu.openmmo.db.jooq.Keys;
import de.fiereu.openmmo.db.jooq.Public;
import de.fiereu.openmmo.db.jooq.tables.Permissions.PermissionsPath;
import de.fiereu.openmmo.db.jooq.tables.Server.ServerPath;
import de.fiereu.openmmo.db.jooq.tables.records.ServerPermissionRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ServerPermission extends TableImpl<ServerPermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.server_permission</code>
     */
    public static final ServerPermission SERVER_PERMISSION = new ServerPermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServerPermissionRecord> getRecordType() {
        return ServerPermissionRecord.class;
    }

    /**
     * The column <code>public.server_permission.server_id</code>.
     */
    public final TableField<ServerPermissionRecord, Integer> SERVER_ID = createField(DSL.name("server_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.server_permission.permission_id</code>.
     */
    public final TableField<ServerPermissionRecord, Integer> PERMISSION_ID = createField(DSL.name("permission_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private ServerPermission(Name alias, Table<ServerPermissionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ServerPermission(Name alias, Table<ServerPermissionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.server_permission</code> table reference
     */
    public ServerPermission(String alias) {
        this(DSL.name(alias), SERVER_PERMISSION);
    }

    /**
     * Create an aliased <code>public.server_permission</code> table reference
     */
    public ServerPermission(Name alias) {
        this(alias, SERVER_PERMISSION);
    }

    /**
     * Create a <code>public.server_permission</code> table reference
     */
    public ServerPermission() {
        this(DSL.name("server_permission"), null);
    }

    public <O extends Record> ServerPermission(Table<O> path, ForeignKey<O, ServerPermissionRecord> childPath, InverseForeignKey<O, ServerPermissionRecord> parentPath) {
        super(path, childPath, parentPath, SERVER_PERMISSION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ServerPermissionPath extends ServerPermission implements Path<ServerPermissionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ServerPermissionPath(Table<O> path, ForeignKey<O, ServerPermissionRecord> childPath, InverseForeignKey<O, ServerPermissionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ServerPermissionPath(Name alias, Table<ServerPermissionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ServerPermissionPath as(String alias) {
            return new ServerPermissionPath(DSL.name(alias), this);
        }

        @Override
        public ServerPermissionPath as(Name alias) {
            return new ServerPermissionPath(alias, this);
        }

        @Override
        public ServerPermissionPath as(Table<?> alias) {
            return new ServerPermissionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ServerPermissionRecord> getPrimaryKey() {
        return Keys.SERVER_PERMISSION_PKEY;
    }

    @Override
    public List<ForeignKey<ServerPermissionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SERVER_PERMISSION__SERVER_PERMISSION_SERVER_ID_FKEY, Keys.SERVER_PERMISSION__SERVER_PERMISSION_PERMISSION_ID_FKEY);
    }

    private transient ServerPath _server;

    /**
     * Get the implicit join path to the <code>public.server</code> table.
     */
    public ServerPath server() {
        if (_server == null)
            _server = new ServerPath(this, Keys.SERVER_PERMISSION__SERVER_PERMISSION_SERVER_ID_FKEY, null);

        return _server;
    }

    private transient PermissionsPath _permissions;

    /**
     * Get the implicit join path to the <code>public.permissions</code> table.
     */
    public PermissionsPath permissions() {
        if (_permissions == null)
            _permissions = new PermissionsPath(this, Keys.SERVER_PERMISSION__SERVER_PERMISSION_PERMISSION_ID_FKEY, null);

        return _permissions;
    }

    @Override
    public ServerPermission as(String alias) {
        return new ServerPermission(DSL.name(alias), this);
    }

    @Override
    public ServerPermission as(Name alias) {
        return new ServerPermission(alias, this);
    }

    @Override
    public ServerPermission as(Table<?> alias) {
        return new ServerPermission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ServerPermission rename(String name) {
        return new ServerPermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ServerPermission rename(Name name) {
        return new ServerPermission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ServerPermission rename(Table<?> name) {
        return new ServerPermission(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerPermission where(Condition condition) {
        return new ServerPermission(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerPermission where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerPermission where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerPermission where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServerPermission where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServerPermission where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServerPermission where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServerPermission where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerPermission whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerPermission whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
