/*
 * This file is generated by jOOQ.
 */
package de.fiereu.openmmo.db.jooq.tables;


import de.fiereu.openmmo.db.jooq.Keys;
import de.fiereu.openmmo.db.jooq.Public;
import de.fiereu.openmmo.db.jooq.tables.Server.ServerPath;
import de.fiereu.openmmo.db.jooq.tables.records.ServerNodeRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.postgres.extensions.bindings.InetBinding;
import org.jooq.postgres.extensions.types.Inet;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ServerNode extends TableImpl<ServerNodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.server_node</code>
     */
    public static final ServerNode SERVER_NODE = new ServerNode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServerNodeRecord> getRecordType() {
        return ServerNodeRecord.class;
    }

    /**
     * The column <code>public.server_node.id</code>.
     */
    public final TableField<ServerNodeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.server_node.server_id</code>.
     */
    public final TableField<ServerNodeRecord, Integer> SERVER_ID = createField(DSL.name("server_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.server_node.ipv4</code>.
     */
    public final TableField<ServerNodeRecord, Inet> IPV4 = createField(DSL.name("ipv4"), DefaultDataType.getDefaultDataType("\"pg_catalog\".\"inet\"").nullable(false), this, "", new InetBinding());

    /**
     * The column <code>public.server_node.ipv6</code>.
     */
    public final TableField<ServerNodeRecord, Inet> IPV6 = createField(DSL.name("ipv6"), DefaultDataType.getDefaultDataType("\"pg_catalog\".\"inet\"").nullable(false), this, "", new InetBinding());

    /**
     * The column <code>public.server_node.port</code>.
     */
    public final TableField<ServerNodeRecord, Integer> PORT = createField(DSL.name("port"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.server_node.created_at</code>.
     */
    public final TableField<ServerNodeRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private ServerNode(Name alias, Table<ServerNodeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ServerNode(Name alias, Table<ServerNodeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.server_node</code> table reference
     */
    public ServerNode(String alias) {
        this(DSL.name(alias), SERVER_NODE);
    }

    /**
     * Create an aliased <code>public.server_node</code> table reference
     */
    public ServerNode(Name alias) {
        this(alias, SERVER_NODE);
    }

    /**
     * Create a <code>public.server_node</code> table reference
     */
    public ServerNode() {
        this(DSL.name("server_node"), null);
    }

    public <O extends Record> ServerNode(Table<O> path, ForeignKey<O, ServerNodeRecord> childPath, InverseForeignKey<O, ServerNodeRecord> parentPath) {
        super(path, childPath, parentPath, SERVER_NODE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ServerNodePath extends ServerNode implements Path<ServerNodeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ServerNodePath(Table<O> path, ForeignKey<O, ServerNodeRecord> childPath, InverseForeignKey<O, ServerNodeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ServerNodePath(Name alias, Table<ServerNodeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ServerNodePath as(String alias) {
            return new ServerNodePath(DSL.name(alias), this);
        }

        @Override
        public ServerNodePath as(Name alias) {
            return new ServerNodePath(alias, this);
        }

        @Override
        public ServerNodePath as(Table<?> alias) {
            return new ServerNodePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ServerNodeRecord, Integer> getIdentity() {
        return (Identity<ServerNodeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ServerNodeRecord> getPrimaryKey() {
        return Keys.SERVER_NODE_PKEY;
    }

    @Override
    public List<UniqueKey<ServerNodeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.SERVER_NODE_IPV6_IPV4_PORT_KEY);
    }

    @Override
    public List<ForeignKey<ServerNodeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SERVER_NODE__SERVER_NODE_SERVER_ID_FKEY);
    }

    private transient ServerPath _server;

    /**
     * Get the implicit join path to the <code>public.server</code> table.
     */
    public ServerPath server() {
        if (_server == null)
            _server = new ServerPath(this, Keys.SERVER_NODE__SERVER_NODE_SERVER_ID_FKEY, null);

        return _server;
    }

    @Override
    public ServerNode as(String alias) {
        return new ServerNode(DSL.name(alias), this);
    }

    @Override
    public ServerNode as(Name alias) {
        return new ServerNode(alias, this);
    }

    @Override
    public ServerNode as(Table<?> alias) {
        return new ServerNode(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ServerNode rename(String name) {
        return new ServerNode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ServerNode rename(Name name) {
        return new ServerNode(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ServerNode rename(Table<?> name) {
        return new ServerNode(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerNode where(Condition condition) {
        return new ServerNode(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerNode where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerNode where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerNode where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServerNode where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServerNode where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServerNode where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServerNode where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerNode whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerNode whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
