/*
 * This file is generated by jOOQ.
 */
package de.fiereu.openmmo.db.jooq;


import de.fiereu.openmmo.db.jooq.tables.Character;
import de.fiereu.openmmo.db.jooq.tables.Container;
import de.fiereu.openmmo.db.jooq.tables.Inventory;
import de.fiereu.openmmo.db.jooq.tables.Item;
import de.fiereu.openmmo.db.jooq.tables.OwnedItem;
import de.fiereu.openmmo.db.jooq.tables.Permissions;
import de.fiereu.openmmo.db.jooq.tables.PgpArmorHeaders;
import de.fiereu.openmmo.db.jooq.tables.Pokemon;
import de.fiereu.openmmo.db.jooq.tables.Server;
import de.fiereu.openmmo.db.jooq.tables.ServerNode;
import de.fiereu.openmmo.db.jooq.tables.ServerPermission;
import de.fiereu.openmmo.db.jooq.tables.ServerToken;
import de.fiereu.openmmo.db.jooq.tables.User;
import de.fiereu.openmmo.db.jooq.tables.UserPermission;
import de.fiereu.openmmo.db.jooq.tables.records.PgpArmorHeadersRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.character</code>.
     */
    public final Character CHARACTER = Character.CHARACTER;

    /**
     * The table <code>public.container</code>.
     */
    public final Container CONTAINER = Container.CONTAINER;

    /**
     * The table <code>public.inventory</code>.
     */
    public final Inventory INVENTORY = Inventory.INVENTORY;

    /**
     * The table <code>public.item</code>.
     */
    public final Item ITEM = Item.ITEM;

    /**
     * The table <code>public.owned_item</code>.
     */
    public final OwnedItem OWNED_ITEM = OwnedItem.OWNED_ITEM;

    /**
     * The table <code>public.permissions</code>.
     */
    public final Permissions PERMISSIONS = Permissions.PERMISSIONS;

    /**
     * The table <code>public.pgp_armor_headers</code>.
     */
    public final PgpArmorHeaders PGP_ARMOR_HEADERS = PgpArmorHeaders.PGP_ARMOR_HEADERS;

    /**
     * Call <code>public.pgp_armor_headers</code>.
     */
    public static Result<PgpArmorHeadersRecord> PGP_ARMOR_HEADERS(
          Configuration configuration
        , String __1
    ) {
        return configuration.dsl().selectFrom(de.fiereu.openmmo.db.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
              __1
        )).fetch();
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          String __1
    ) {
        return de.fiereu.openmmo.db.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          Field<String> __1
    ) {
        return de.fiereu.openmmo.db.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * The table <code>public.pokemon</code>.
     */
    public final Pokemon POKEMON = Pokemon.POKEMON;

    /**
     * The table <code>public.server</code>.
     */
    public final Server SERVER = Server.SERVER;

    /**
     * The table <code>public.server_node</code>.
     */
    public final ServerNode SERVER_NODE = ServerNode.SERVER_NODE;

    /**
     * The table <code>public.server_permission</code>.
     */
    public final ServerPermission SERVER_PERMISSION = ServerPermission.SERVER_PERMISSION;

    /**
     * The table <code>public.server_token</code>.
     */
    public final ServerToken SERVER_TOKEN = ServerToken.SERVER_TOKEN;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>public.user_permission</code>.
     */
    public final UserPermission USER_PERMISSION = UserPermission.USER_PERMISSION;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Character.CHARACTER,
            Container.CONTAINER,
            Inventory.INVENTORY,
            Item.ITEM,
            OwnedItem.OWNED_ITEM,
            Permissions.PERMISSIONS,
            PgpArmorHeaders.PGP_ARMOR_HEADERS,
            Pokemon.POKEMON,
            Server.SERVER,
            ServerNode.SERVER_NODE,
            ServerPermission.SERVER_PERMISSION,
            ServerToken.SERVER_TOKEN,
            User.USER,
            UserPermission.USER_PERMISSION
        );
    }
}
